<a href="https://colab.research.google.com/github/cheskamuro/Linear-Algebra-58019/blob/main/Application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##The price of one apple and one orange

In [8]:
import numpy as np
A = np.array([[20,10],[17,22]])
B = np.array([[350],[500]])
print(A)
print(B)
X = np.linalg.solve(A,B)
print(X)

[[20 10]
 [17 22]]
[[350]
 [500]]
[[10.]
 [15.]]


In [4]:
inv_A= np.linalg.inv(A)
print(inv_A)
X = np.linalg.inv(A).dot(B)
print(X)

[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]
[[10.]
 [15.]]


In [5]:
X = np.dot(inv_A,B)
print(X)

[[10.]
 [15.]]
