<a href="https://colab.research.google.com/github/cheskamuro/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Problem 1

In [ ]:
eq1=np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2=np.array([[89,],[89],[95]])
amt=np.linalg.inv(eq1).dot(eq2)
print(amt)

[[13.]
 [57.]
 [19.]]


###Problem 2 - Because the following equation is a singular matrix with a determinant of 0, there is a problem with solving it. This is also the reason why the dot product and inverse are missing. Singular matrices are square matrices with a zero determinant, just for clarity. You won't be able to reverse a matrix like this.


In [ ]:
import numpy as np
A=np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
inv_A=np.linalg.inv(A) 
print(inv_A)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]


LinAlgError: ignored

In [ ]:
B=np.array([[[5],[15],[-20]]]) #creation of matrix B
print(B)

[[[  5]
  [ 15]
  [-20]]]


In [ ]:
X=np.linalg.inv(A).dot(B)
print(X)

LinAlgError: ignored

In [ ]:
X=np.dot(inv_A,B)
print(X)

ValueError: ignored

###Problem 3


In [ ]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8, 5, -6],[-12, 9, 12],[-3, -3, 5]]) #code to display the matrix
print(A)

w,v = np.linalg.eig(A) #code to solve for eigenvalues and eigenvectors
print("The eigenvalues is/are:",w)
print("The right eigenvectors are:",v)

x = v.round()
print(x)

[[  8   5  -6]
 [-12   9  12]
 [ -3  -3   5]]
The eigenvalues is/are: [10.+9.74679434j 10.-9.74679434j  2.+0.j        ]
The right eigenvectors are: [[-6.19826768e-02-0.44653265j -6.19826768e-02+0.44653265j
   7.07106781e-01+0.j        ]
 [ 8.56977879e-01+0.j          8.56977879e-01-0.j
  -1.66861154e-16+0.j        ]
 [ 9.43214647e-03+0.24953295j  9.43214647e-03-0.24953295j
   7.07106781e-01+0.j        ]]
[[-0.-0.j -0.+0.j  1.+0.j]
 [ 1.+0.j  1.-0.j -0.+0.j]
 [ 0.+0.j  0.-0.j  1.+0.j]]
