<a href="https://colab.research.google.com/github/cheskamuro/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Question 1: Create a Python code that displays a square matrix whose length is 5.

In [43]:
import numpy as np
SM = np.array ([[1,0,0,0,1],[2,0,0,0,2],[3,0,0,0,3],[4,0,0,0,4],[5,0,0,0,5]]) #code of a 5x5 matrix
print(SM)

[[1 0 0 0 1]
 [2 0 0 0 2]
 [3 0 0 0 3]
 [4 0 0 0 4]
 [5 0 0 0 5]]


###Question 2: Create a Python code that displays a square matrix whose elements below the principal diagonal are zero.

In [39]:
import numpy as np
SM= np.array ([[2,2,2,],[0,2,2],[0,0,2]]) #code of a square matrix whose elements below the principal diagonal are zero
print(SM)

[[2 2 2]
 [0 2 2]
 [0 0 2]]


###Question 3. Create a Python code that displays a square matrix which is symmetrical.

In [53]:
import numpy as np
SM = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]]) #code of a square matrix that is symmetrical.
print(SM)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


###Question 4: What is the inverse of matrix C? Show your solution by python coding.




In [4]:
import numpy as np
C=np.array([[[1,2,3],[2,3,3],[3,4,-2]]]) #creation of matrix C
print(C)
inv_A=np.linalg.inv(C) #creation of the inverse of matrix C
print(inv_A)

[[[ 1  2  3]
  [ 2  3  3]
  [ 3  4 -2]]]
[[[-3.6  3.2 -0.6]
  [ 2.6 -2.2  0.6]
  [-0.2  0.4 -0.2]]]


##Question 5: What is the determinant of the given matrix in Question 4? Show your solution by python coding.

In [11]:
C=np.array([[[1,2,3],[2,3,3],[3,4,-2]]]) #creation of matrix C
print(C)
detOfC = np.linalg.det(C) #creation of the determinant of matrix C
print("Determinant of Matrix C:")
print(int(detOfC))

[[[ 1  2  3]
  [ 2  3  3]
  [ 3  4 -2]]]
Determinant of Matrix C:
5


##Question 6: Find the roots of the linear equations by showing its python codes.

In [8]:
eq = np.array([[5,4,1],[10,9,4],[10,13,15]])
const = np.array([[[3.4],[8.8],[19.2]]])
roots = np.linalg.inv(eq)@const #creation of the roots of the linear equation
print(roots)

[[[0.2]
  [0.4]
  [0.8]]]
