<a href="https://colab.research.google.com/github/cheskamuro/Linear-Algebra-58019/blob/main/Phython_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Representing Vectors

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is',A)
print('Vector B is',B)

Vector A is [4 3]
Vector B is [ 2 -5]


##Describing Vestors in NumPy




In [7]:
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])
pool.shape
pool.ndim

2

In [11]:
U = np.array([[1,2,3],[4,5,6]])
U
U.shape
U.ndim
U.size

6

#Space

##Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations

###Addition of Vectors

In [17]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [20]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
resultant

array([1, 1, 0])

##Subraction of Vector

In [24]:
#You will subtract the compornents of addend2 from addend1 : addend1-addend2
difference = addend1-addend2
difference

array([-1, -1,  0])

In [27]:
difference2 = np.subtract(addend1,addend2)
difference2

array([-1, -1,  0])

In [21]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
difference = addend1 - addend2
difference

array([-1, -1,  0])

In [22]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.subtract(addend1,addend2)
resultant

array([-1, -1,  0])

##Scaling

In [28]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

##Cross Product

In [30]:
import numpy as np
A  = np.array([2,3,4]) #initialize arrays
B  = np.array([1,7,1])
output = np.cross(A,B) #compute the cross product of A and B
print(output)


[-25   2  11]
