<a href="https://colab.research.google.com/github/cheskamuro/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Problem 1

In [22]:
import numpy as np #Problem 1
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,],[3,4],[5,6]])
dot = np.dot(A,B)
print(dot) #a

[[22 28]
 [49 64]]


In [24]:
import numpy as np #Problem 1
D = np.array([[1,2,],[3,4]])
print(D + D) #b

[[2 4]
 [6 8]]


In [23]:
import numpy as np #Problem 1
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(2*C) #c

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


##Problem 2

In [28]:
import numpy as np #Problem 2
x = np.array([5,3,-1])

print(x)
print('\nType of array:', type(x))   #Array
print('Size of array:', x.size)      #Size
print('Shape of array:', x.shape)    #Shape
print('Dimension of array:', x.ndim) #Dimension

[ 5  3 -1]

Type of array: <class 'numpy.ndarray'>
Size of array: 3
Shape of array: (3,)
Dimension of array: 1
